### PR TITLE
PR for code review.

### PR DESCRIPTION
**Pull request by praz99**
- This project is the clone of [newsweek.com](newsweek.com).
- Bootstrap classes have been used where able possible.
-Media queries have been used for making the page responsive in addition to the bootstrap.

### CODE REVIEW

**Review by christianotieno — CHANGES_REQUESTED** [review]
## Awesome work @praz99  

### [The clone](https://raw.githack.com/praz99/newsweekClone/mainpage/index.html) shows good use of CSS bootstrap classes and it is very responsive. :100: 

A few required changes: Note that for this project, we have to make sure nothing is messed up. Please see the difference in the source page and the clone below: 

| [Current clone](https://raw.githack.com/praz99/newsweekClone/mainpage/index.html) | [Source Page](https://www.newsweek.com/) |
|:-----:|:-----:|
|clone|source|
- Kindly fix the centring of the contents. The `container` bootstrap class could come in handy here.

- Validate your markup. Use this [tool](https://validator.w3.org/nu/#textarea) for that.

#### :recycle:  Make these changes and submit another code review request. :+1: 

#### Feel free to reach me on slack if you having issues implementing these features. :+1: 

Good luck with your next submission. :star2: 

Cheers
[Christian Otieno](https://github.com/christianotieno)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

**Review by mikenath223 — CHANGES_REQUESTED** [review]
Hi @praz99  👋

You've done quite well on the layout of this project.
However, kindly fix this:

- [ ] - There are whole sections with images not showing. Kindly fix this. I will advise that you download all images in an asset folder and serve them to your project from there.
ice_screenshot_20200422-113813


Kindly fix these issue and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by mikenath223** [comment]
This review request has been marked as invalid.

### STATUS: INVALID REQUEST ✖

Reason:
- Please fix the issue referenced in the previous review.

Perhaps you can do this if you don't prefer downloading all images. Simply right-click on the image you want to copy and when the context menu comes out instead of clicking on `Copy link address`  click on `Copy image address` instead. That would prevent the issue of your images not showing.

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — APPROVED** [review]
## Status: Require changes 🏆 🎈 

Hi @praz99, congratulations on a great job done 👍 The project now meets all the minimum requirements 😄 Going forward, let us improve our commits messages, for example, ```add``` instead of ```added```, ```fix``` instead of ```fixed``` etc

Go ahead and merge to master and submit the project completion form
_Happy coding_ 👨‍💻 
Daniel Larbi Addo on slack

**Pull request merged**
